- file(clean_and_normalize.yaml)
- type: switch
  configs:
    - file(es/spelling_corruption.yaml)
    - type: none
  probabilities:
    - 0.8
    - 0.2
- type: switch
  configs: 
    - type: chain
      configs:
        - file(whitespace/whitespace_corruption.yaml)
        - file(mask/char_mask_corruption.yaml)
    - file(mask/word_mask_corruption.yaml)
  probabilities:
    - 0.8
    - 0.2
- type: language_dropout
  prob: 0.25
